# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3b620bbe54443979930ec372632d5be"
name = "event-attendees-modern"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_metaobjects,write_metaobjects,read_inventory,write_inventory"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
