# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c34d7e26ba1f5ce83a7dc4f409f5388"
name = "event-attendees"
application_url = "https://magnificent-alignment-production-373e.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [ "https://magnificent-alignment-production-373e.up.railway.app/api/auth" ]
